const STEPS=[
  {name:'Show empty hand',hint:'Open palm with nothing in it.',guide:'Start with an empty palm. Spread all five fingers and face your palm to the camera.',checks:['Five fingers open','Palm faces camera','Nothing in palm']},
  {name:'Pick up the tablet',hint:'Hold any visible test object near your palm.',guide:'Now pick up the tablet. For testing, any visible object is accepted. Hold it naturally while keeping it visible to the camera.',checks:['Object is visible','Object stays near your palm','Hold for one second']},
  {name:'Tablet to mouth',hint:'Move the same hand to the oval.',guide:'After the short pause, bring the tablet with the same hand to your mouth oval and hold it there.',checks:['Keep the tablet in hand','Move to the oval','Hold for one second']},
  {name:'Show empty hand again',hint:'Remove the tablet and show your palm.',guide:'After another pause, remove the tablet and return your open, empty palm to the camera.',checks:['Remove the tablet','Open five fingers','Palm faces camera']},
  {name:'Drink water',hint:'Bring a cup to the oval.',guide:'After the pause, bring a cup or any test object to the mouth oval and hold it there.',checks:['Hold a cup/object','Move to the oval','Hold for one second']},
];
const CONFIG={palmHold:700,objectHold:1000,mouthHold:1000,waterHold:1000,gapMs:1000,mouthX:.5,mouthY:.34,mouthRadius:.14,objectThreshold:.085};
let stream=null,hands=null,tracking=false,mode='idle',step=0,holdSince=0,gapUntil=0,baseline=null,stepScores=[0,0,0,0,0],demoTimer=null;
const $=id=>document.getElementById(id),video=$('video'),canvas=$('landmarks'),ctx=canvas.getContext('2d');
const cropCanvas=document.createElement('canvas');cropCanvas.width=48;cropCanvas.height=48;const cropCtx=cropCanvas.getContext('2d',{willReadFrequently:true});let lastCropBox=null;

function feedback(kind,title,text){$('feedback').className=`feedback ${kind}`;$('feedbackTitle').textContent=title;$('feedbackText').textContent=text}
function cameraBadge(kind,text){$('cameraBadge').className=`camera-badge ${kind||''}`;$('cameraBadge').textContent=text}
function setCameraMessage(text){$('cameraMessage').textContent=text}
function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function render(){const index=mode==='idle'?-1:mode==='done'?5:step;const progress=stepScores.reduce((t,x,i)=>t+x*[.2,.2,.25,.2,.15][i],0);$('scoreValue').textContent=`${Math.round(progress*100)}%`;$('scoreBar').style.width=`${progress*100}%`;$('scoreText').textContent=mode==='done'?'All five stages checked. This is a gesture estimate, not proof of swallowing.':'The app will not advance until the current gesture is detected.';$('stateBadge').textContent=mode==='idle'?'Not started':mode==='done'?'Complete':`Step ${step+1} of 5`;$('stateBadge').className=`state-badge ${mode==='done'?'good':''}`;$('steps').innerHTML=STEPS.map((item,i)=>`<div class="step ${i===index?'active':''} ${stepScores[i]?'done':''}"><span class="step-number">${stepScores[i]?'✓':i+1}</span><div><div class="step-name">${item.name}</div><div class="step-hint">${item.hint}</div></div><span class="step-mark">${stepScores[i]?`${Math.round(stepScores[i]*100)}%`:''}</span></div>`).join('');if(index<0){$('coachTitle').textContent='Start the camera';$('coachText').textContent='Your camera preview will appear before hand recognition starts.';$('coachList').innerHTML=''}else if(index<5){const item=STEPS[index];$('coachTitle').textContent=item.name;$('coachText').textContent=item.guide;$('coachList').innerHTML=item.checks.map(x=>`<div class="coach-check">${x}</div>`).join('')}else{$('coachTitle').textContent='All five stages checked';$('coachText').textContent='The complete sequence was observed.';$('coachList').innerHTML=''}}
function reset(){step=0;holdSince=0;gapUntil=0;baseline=null;stepScores=[0,0,0,0,0];mode='idle';$('mouthZone').classList.add('hidden');$('mouthZone').classList.remove('near');ctx.clearRect(0,0,canvas.width,canvas.height);render()}
function handInfo(hand){const wrist=hand[0],palm=hand[9],pairs=[[8,6],[12,10],[16,14],[20,18]];let fingers=0;for(const [tip,pip] of pairs)if(hand[tip].y<hand[pip].y)fingers++;if(distance(hand[4],wrist)>distance(hand[3],wrist)*1.08)fingers++;const open=fingers>=4;const near=[hand[8],hand[12],hand[0]].some(p=>Math.hypot(p.x-CONFIG.mouthX,p.y-CONFIG.mouthY)<CONFIG.mouthRadius);return {fingers,open,near}}
function palmPixels(hand){if(!video.videoWidth)return null;const size=Math.max(30,Math.round(video.videoWidth*distance(hand[0],hand[9])*.7));const x=Math.min(Math.max(0,hand[9].x*video.videoWidth-size/2),video.videoWidth-size),y=Math.min(Math.max(0,hand[9].y*video.videoHeight-size/2),video.videoHeight-size);cropCtx.clearRect(0,0,48,48);cropCtx.drawImage(video,x,y,size,size,0,0,48,48);lastCropBox={x,y,size};return cropCtx.getImageData(0,0,48,48).data}
function objectDelta(hand){const pixels=palmPixels(hand);if(!pixels||!baseline)return 0;let total=0;for(let i=0;i<pixels.length;i+=4)total+=(Math.abs(pixels[i]-baseline[i])+Math.abs(pixels[i+1]-baseline[i+1])+Math.abs(pixels[i+2]-baseline[i+2]))/3;return total/(pixels.length/4)/255}
function saveBaseline(hand){baseline=palmPixels(hand)}
function drawHand(hand){if(!video.videoWidth)return;canvas.width=video.videoWidth;canvas.height=video.videoHeight;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.lineWidth=4;ctx.strokeStyle='#70e0a2';ctx.fillStyle='#fff';const links=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[17,18],[18,19],[19,20],[0,17]];for(const [a,b] of links){ctx.beginPath();ctx.moveTo(hand[a].x*canvas.width,hand[a].y*canvas.height);ctx.lineTo(hand[b].x*canvas.width,hand[b].y*canvas.height);ctx.stroke()}for(const p of hand){ctx.beginPath();ctx.arc(p.x*canvas.width,p.y*canvas.height,5,0,Math.PI*2);ctx.fill()}}
function nextStage(score,notice){stepScores[step]=score;step++;holdSince=0;gapUntil=Date.now()+CONFIG.gapMs;feedback('neutral','Small pause',`${notice} Get ready for the next stage.`);render()}
function holdCheck(ok,ms,goodTitle,goodText,badTitle,badText,success){if(!ok){holdSince=0;feedback('bad',badTitle,badText);return}if(!holdSince)holdSince=Date.now();const remaining=Math.max(0,ms-(Date.now()-holdSince));if(remaining){feedback('good',goodTitle,`${goodText} Hold for ${Math.ceil(remaining/100)/10}s.`);return}holdSince=0;success()}
function updateDebugPanel(delta,objectPresent){const readout=$('debugReadout');if(!readout)return;readout.textContent=`delta=${delta.toFixed(3)} threshold=${CONFIG.objectThreshold.toFixed(3)} → ${objectPresent?'OBJECT PRESENT':'no object / empty'}`;readout.style.color=objectPresent?'#2d9b65':'#a54738';const debugCanvas=$('debugPreview');if(debugCanvas&&lastCropBox&&video.videoWidth){const dctx=debugCanvas.getContext('2d');dctx.imageSmoothingEnabled=false;dctx.clearRect(0,0,96,96);dctx.drawImage(video,lastCropBox.x,lastCropBox.y,lastCropBox.size,lastCropBox.size,0,0,96,96)}}

function onResults(result){if(mode==='idle'||mode==='done'||mode==='demo')return;const hand=result.multiHandLandmarks?.[0];if(!hand){ctx.clearRect(0,0,canvas.width,canvas.height);$('mouthZone').classList.remove('near');feedback('bad','Hand not detected','Move your hand fully into the camera view.');return}drawHand(hand);const info=handInfo(hand);const delta=objectDelta(hand),objectPresent=delta>CONFIG.objectThreshold,emptyPalm=delta<=CONFIG.objectThreshold;updateDebugPanel(delta,objectPresent);$('mouthZone').classList.toggle('near',info.near);if(Date.now()<gapUntil){feedback('neutral','Pause','Wait a moment, then follow the next instruction.');return}
  if(step===0)holdCheck(info.open&&emptyPalm,CONFIG.palmHold,'Empty palm detected','Keep your empty palm still.','Show your empty palm','Keep the palm empty, spread five fingers, and face it to the camera.',()=>{saveBaseline(hand);nextStage(.95,'Now pick up the tablet or test object.')});
  else if(step===1)holdCheck(objectPresent,CONFIG.objectHold,'Tablet detected','Keep the object visible to the camera.','Pick up the tablet','Hold the object so the camera can see it near your palm.',()=>nextStage(.9,'Tablet detected. Now move it to your mouth.'));
  else if(step===2)holdCheck(info.near&&objectPresent,CONFIG.mouthHold,'Tablet at mouth','Keep the tablet at the green oval.','Move tablet to mouth','Keep the tablet in your hand and move it into the mouth oval.',()=>nextStage(.9,'Mouth stage complete. Remove the tablet and show an empty palm.'));
  else if(step===3)holdCheck(info.open&&emptyPalm,CONFIG.palmHold,'Empty palm detected','Keep the palm open and empty.','Show empty palm again','Remove the tablet, spread five fingers, and face the empty palm to the camera.',()=>nextStage(.95,'Empty palm confirmed. Get ready to drink water.'));
  else if(step===4)holdCheck(info.near&&objectPresent,CONFIG.waterHold,'Water position detected','Keep the cup or test object at the green oval.','Bring water to mouth','Bring a cup or visible test object to the mouth oval and hold it there.',()=>{stepScores[4]=.85;mode='done';feedback('good','All five stages correct','The complete tablet-and-water gesture sequence was observed.');render()})
}
async function track(){if(!tracking||!hands)return;if(video.readyState>=2&&video.videoWidth)try{await hands.send({image:video})}catch(error){tracking=false;cameraBadge('error','Hand tracker error');feedback('bad','Hand tracker stopped','Reload the page and try again.')}if(tracking)requestAnimationFrame(track)}
async function startHands(){if(!window.Hands){cameraBadge('error','Tracker unavailable');feedback('bad','Hand tracker did not load','Check internet access and reload.');return}hands=new Hands({locateFile:file=>`https://cdn.jsdelivr.net/npm/@mediapipe/hands/${file}`});hands.setOptions({maxNumHands:1,modelComplexity:0,minDetectionConfidence:.55,minTrackingConfidence:.55});hands.onResults(onResults);tracking=true;track()}
async function startCamera(){if(location.protocol==='file:'){cameraBadge('error','Use localhost');feedback('bad','Open through the local server','Use http://localhost:8000, not the file directly.');return}if(!navigator.mediaDevices?.getUserMedia){cameraBadge('error','Camera unavailable');feedback('bad','Camera API unavailable','Use Chrome at http://localhost:8000.');return}if(stream)stream.getTracks().forEach(track=>track.stop());reset();mode='live';setCameraMessage('Connecting to camera...');cameraBadge('','Connecting...');feedback('neutral','Connecting to camera','Allow camera access if Chrome asks.');try{stream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});video.srcObject=stream;video.onloadeddata=()=>{cameraBadge('live','Camera preview is live');setCameraMessage('Show your empty hand');};await video.play();$('mouthZone').classList.remove('hidden');feedback('neutral','Step 1: empty hand','Show five open fingers with nothing in your palm.');setCameraMessage('Show empty hand');await startHands()}catch(error){mode='idle';cameraBadge('error','Camera failed');setCameraMessage('Camera could not start');const messages={NotAllowedError:'Chrome or Windows blocked camera access.',NotFoundError:'No camera was found.',NotReadableError:'The camera is busy in another app.',SecurityError:'Use http://localhost:8000 or HTTPS.'};feedback('bad','Camera did not start',messages[error.name]||`${error.name}: ${error.message||'unknown error'}`);render()}}
function demo(){if(demoTimer)clearInterval(demoTimer);mode='demo';reset();mode='demo';let i=0;const events=[['good','Empty palm detected','Now pick up a tablet or test object.'],['bad','Tablet not detected','Pick up the object and keep it visible.'],['good','Tablet detected','Pause, then move it to your mouth.'],['good','Tablet at mouth','Pause, then remove the tablet.'],['bad','Palm is not empty','Remove the tablet and show your empty palm.'],['good','Empty palm detected','Pause, then get a cup.'],['bad','Water not detected','Bring the cup to the mouth oval.'],['good','All five stages correct','The full sequence was observed.']];const tick=()=>{const e=events[i++];if(!e){clearInterval(demoTimer);mode='done';stepScores=[.95,.9,.9,.95,.85];render();return}feedback(e[0],e[1],e[2]);if(e[0]==='good'&&step<5){stepScores[step]=[.95,.9,.9,.95,.85][step];step++}render()};$('mouthZone').classList.remove('hidden');tick();demoTimer=setInterval(tick,900)}
const thresholdSlider=$('thresholdSlider');
if(thresholdSlider){thresholdSlider.value=CONFIG.objectThreshold;thresholdSlider.oninput=event=>{CONFIG.objectThreshold=Number(event.target.value);$('thresholdValue').textContent=CONFIG.objectThreshold.toFixed(3)}}
$('startBtn').onclick=startCamera;$('demoBtn').onclick=demo;reset();
