const STEPS=[
  {name:'Show empty hand',hint:'Open palm with nothing in it.',guide:'Start with an empty palm. Spread all five fingers and face your palm to the camera.',checks:['Five fingers open','Palm faces camera','Nothing in palm']},
  {name:'Pick up the tablet',hint:'Hold any visible test object near your palm.',guide:'Now pick up the tablet. For testing, any visible object is accepted. Hold it naturally while keeping it visible to the camera.',checks:['Object is visible','Object stays near your palm','Hold for one second']},
  {name:'Tablet to mouth',hint:'Move the same hand to the oval.',guide:'After the short pause, bring the tablet with the same hand to your mouth oval and hold it there.',checks:['Keep the tablet in hand','Move to the oval','Hold for one second']},
  {name:'Show empty hand again',hint:'Remove the tablet and show your palm.',guide:'After another pause, remove the tablet and return your open, empty palm to the camera.',checks:['Remove the tablet','Open five fingers','Palm faces camera']},
  {name:'Drink water',hint:'Bring a cup to the oval.',guide:'After the pause, bring a cup or any test object to the mouth oval and hold it there.',checks:['Hold a cup/object','Move to the oval','Hold for one second']},
];
const CONFIG={palmHold:700,objectHold:1000,mouthHold:1000,waterHold:1000,gapMs:1000,mouthX:.5,mouthY:.34,mouthRadius:.14,objectThreshold:.085};
let stream=null,hands=null,tracking=false,mode='idle',step=0,holdSince=0,gapUntil=0,baseline=null,stepScores=[0,0,0,0,0],demoTimer=null,lastProgressAt=0,showRetry=false;
let currentRoutineId='morning_medicine',eventPosted=false,alarmReminder=null,alarmRepeatTimer=null,audioUnlocked=false,unlockedAudioContext=null,walkRoutine=null,walkState=null,walkTimerId=null,motionHandler=null;
const SESSION_TIMEOUT_MS=120000,WALK_GOAL_SECONDS=20*60,MOTION_THRESHOLD=2.5;
const $=id=>document.getElementById(id),video=$('video'),canvas=$('landmarks'),ctx=canvas.getContext('2d');
const cropCanvas=document.createElement('canvas');cropCanvas.width=48;cropCanvas.height=48;const cropCtx=cropCanvas.getContext('2d',{willReadFrequently:true});let lastCropBox=null;

function feedback(kind,title,text){$('feedback').className=`feedback ${kind}`;$('feedbackTitle').textContent=title;$('feedbackText').textContent=text}
function cameraBadge(kind,text){$('cameraBadge').className=`camera-badge ${kind||''}`;$('cameraBadge').textContent=text}
function setCameraMessage(text){$('cameraMessage').textContent=text}
async function loadRoutineContext(){try{const response=await fetch('/api/routines');if(!response.ok)return;const routines=await response.json();const preferred=routines.find(item=>item.active&&item.type==='medicine')||routines.find(item=>item.active);if(preferred)currentRoutineId=preferred.id;walkRoutine=routines.find(item=>item.active&&item.type==='walk')||null;renderWalkPanel()}catch(error){console.info('Backend unavailable; continuing in local-only mode.')}}
function unlockAudio(){if(audioUnlocked)return;audioUnlocked=true;try{const AudioContext=window.AudioContext||window.webkitAudioContext;if(AudioContext){unlockedAudioContext=new AudioContext();const buffer=unlockedAudioContext.createBuffer(1,1,22050);const source=unlockedAudioContext.createBufferSource();source.buffer=buffer;source.connect(unlockedAudioContext.destination);source.start(0)}}catch(error){console.info('Audio unlock failed; alarm sound may be silent until a tap.')}$('unlockOverlay')?.classList.add('hidden')}
function playGentleAlert(){try{const AudioContext=window.AudioContext||window.webkitAudioContext;const audio=unlockedAudioContext||(AudioContext&&new AudioContext());if(!audio)return;if(audio.state==='suspended')audio.resume().catch(()=>{});const oscillator=audio.createOscillator();const gain=audio.createGain();oscillator.type='sine';oscillator.frequency.value=660;gain.gain.setValueAtTime(.0001,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.08,audio.currentTime+.04);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.65);oscillator.connect(gain).connect(audio.destination);oscillator.start();oscillator.stop(audio.currentTime+.7)}catch(error){console.info('Alarm sound requires a user gesture.')}}
function showAlarm(reminder){if(alarmReminder)return;alarmReminder=reminder;$('alarmTitle').textContent=`${reminder.type==='medicine'?'💊':'⏰'} Time for ${reminder.label}`;$('alarmText').textContent=`It was scheduled for ${reminder.scheduled_time}. Press Start when you are ready to follow the verification guide.`;$('alarmModal').classList.remove('hidden');playGentleAlert();alarmRepeatTimer=setTimeout(()=>{if(alarmReminder)playGentleAlert()},10*60*1000)}
async function acknowledgeReminder(){const reminder=alarmReminder;if(!reminder)return;currentRoutineId=reminder.routine_id;try{await fetch(`/api/reminders/${encodeURIComponent(reminder.id)}/ack`,{method:'POST'})}catch(error){console.info('Reminder acknowledgement could not be saved.')}if(alarmRepeatTimer)clearTimeout(alarmRepeatTimer);alarmRepeatTimer=null;alarmReminder=null;$('alarmModal').classList.add('hidden');startCamera()}
async function pollReminders(){try{const response=await fetch('/api/pending-reminders');if(!response.ok)return;const reminders=await response.json();const next=reminders[0];if(next&&!alarmReminder)showAlarm(next)}catch(error){}}
function setSessionControls(){const resetButton=$('resetBtn'),retryButton=$('retryBtn');if(resetButton)resetButton.classList.toggle('hidden',mode!=='live');if(retryButton)retryButton.classList.toggle('hidden',!showRetry)}
function stopCameraTracks(){tracking=false;if(stream){stream.getTracks().forEach(track=>track.stop());stream=null}video.pause();video.srcObject=null}
function pauseSession(){stopCameraTracks();mode='idle';showRetry=false;$('mouthZone').classList.add('hidden');setCameraMessage('Press Start camera when ready');cameraBadge('','Camera paused');feedback('neutral','Session paused','No progress was detected for two minutes. Press Start camera to try again.');render()}
function cameraFailure(message){stopCameraTracks();mode='idle';showRetry=true;$('mouthZone').classList.add('hidden');cameraBadge('error','Camera unavailable');setCameraMessage('Camera could not continue');feedback('bad','Camera needs attention',message);render()}
async function postActivityEvent(event){try{const response=await fetch('/api/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(event)});if(!response.ok)throw new Error(`event request failed: ${response.status}`);return true}catch(error){console.info('Activity completed locally; backend event was not saved.');return false}}
function renderWalkPanel(){const panel=$('walkPanel');if(!panel)return;panel.classList.toggle('hidden',!walkRoutine);if(walkRoutine)$('walkGoal').textContent=`Goal: ${Math.round(WALK_GOAL_SECONDS/60)} minutes of movement · ${walkRoutine.label}`}
function requestMotionAccess(){if(!('DeviceMotionEvent' in window))return Promise.resolve(false);if(typeof DeviceMotionEvent.requestPermission==='function')return DeviceMotionEvent.requestPermission().then(permission=>permission==='granted');return Promise.resolve(true)}
function formatDuration(seconds){const minutes=Math.floor(seconds/60);const remaining=seconds%60;return `${minutes}:${String(remaining).padStart(2,'0')}`}
function updateWalkUi(){if(!walkState)return;const totalSeconds=Math.max(0,Math.floor((Date.now()-walkState.startedAt)/1000));const movingRatio=walkState.samples?walkState.movingSamples/walkState.samples:0;$('walkTimer').textContent=formatDuration(totalSeconds);$('walkStatus').textContent=walkState.motionDenied?'Motion access was not available. You can finish, but this check will be uncertain.':walkState.samples?`Movement detected · ${Math.round(movingRatio*100)}% of samples active`:'Waiting for movement…';$('walkStatus').className=`walk-status ${movingRatio>=.6?'good':''}`;if(walkState.movingMs>=WALK_GOAL_SECONDS&&!walkState.finishing)finishWalk(true)}
async function startWalk(){if(!walkRoutine||walkState)return;try{const granted=await requestMotionAccess();walkState={startedAt:Date.now(),lastSampleAt:Date.now()-500,movingMs:0,samples:0,movingSamples:0,motionDenied:!granted,finishing:false};if(granted){motionHandler=event=>{if(!walkState||walkState.finishing)return;const now=Date.now();if(now-walkState.lastSampleAt<500)return;const acceleration=event.accelerationIncludingGravity||event.acceleration;if(!acceleration)return;const x=Number(acceleration.x)||0,y=Number(acceleration.y)||0,z=Number(acceleration.z)||0,magnitude=Math.sqrt(x*x+y*y+z*z),moving=Math.abs(magnitude-9.8)>MOTION_THRESHOLD;walkState.lastSampleAt=now;walkState.samples++;if(moving){walkState.movingSamples++;walkState.movingMs+=Math.min(1000,now-walkState.lastSampleAt+500)}updateWalkUi()};window.addEventListener('devicemotion',motionHandler)}$('startWalkBtn').disabled=true;$('finishWalkBtn').disabled=false;$('walkStatus').textContent=granted?'Walk normally while carrying the phone.':'Motion permission was not granted.';$('walkStatus').className='walk-status bad';walkTimerId=setInterval(updateWalkUi,500);updateWalkUi()}catch(error){walkState={motionDenied:true,startedAt:Date.now(),samples:0,movingSamples:0,movingMs:0,finishing:false};$('walkStatus').textContent='Motion access could not start. You can finish, but this check will be uncertain.';$('walkStatus').className='walk-status bad'}}
async function finishWalk(auto=false){if(!walkState||walkState.finishing)return;walkState.finishing=true;if(motionHandler)window.removeEventListener('devicemotion',motionHandler);motionHandler=null;if(walkTimerId)clearInterval(walkTimerId);walkTimerId=null;const durationSeconds=Math.max(0,Math.round((Date.now()-walkState.startedAt)/1000));const ratio=walkState.samples?walkState.movingSamples/walkState.samples:0;const status=ratio>=.6?'verified':'uncertain';await postActivityEvent({routine_id:walkRoutine.id,timestamp:new Date().toISOString(),status,confidence:ratio,step_confidences:[],duration_seconds:durationSeconds});$('walkTimer').textContent=formatDuration(durationSeconds);$('walkStatus').textContent=status==='verified'?`Walk verified · ${Math.round(durationSeconds/60)} minutes of movement.`:`Walk saved as uncertain · ${Math.round(durationSeconds/60)} minutes. Try to keep moving for most of the check.`;$('walkStatus').className=`walk-status ${status==='verified'?'good':'bad'}`;$('startWalkBtn').disabled=false;$('finishWalkBtn').disabled=true;walkState=null;if(auto)feedback('good','Walk goal reached','Your movement check was saved.')} 
async function postVerificationEvent(){if(eventPosted)return;eventPosted=true;const confidence=stepScores.reduce((sum,value,index)=>sum+value*[.2,.2,.25,.2,.15][index],0);try{const response=await fetch('/api/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({routine_id:currentRoutineId,timestamp:new Date().toISOString(),status:'verified',confidence,step_confidences:stepScores})});if(!response.ok)throw new Error(`event request failed: ${response.status}`)}catch(error){eventPosted=false;console.info('Verification completed locally; backend event was not saved.')}}
function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function render(){const index=mode==='idle'?-1:mode==='done'?5:step;const progress=stepScores.reduce((t,x,i)=>t+x*[.2,.2,.25,.2,.15][i],0);$('scoreValue').textContent=`${Math.round(progress*100)}%`;$('scoreBar').style.width=`${progress*100}%`;$('scoreText').textContent=mode==='done'?'All five stages checked. This is a gesture estimate, not proof of swallowing.':'The app will not advance until the current gesture is detected.';$('stateBadge').textContent=mode==='idle'?'Not started':mode==='done'?'Complete':`Step ${step+1} of 5`;$('stateBadge').className=`state-badge ${mode==='done'?'good':''}`;$('steps').innerHTML=STEPS.map((item,i)=>`<div class="step ${i===index?'active':''} ${stepScores[i]?'done':''}"><span class="step-number">${stepScores[i]?'✓':i+1}</span><div><div class="step-name">${item.name}</div><div class="step-hint">${item.hint}</div></div><span class="step-mark">${stepScores[i]?`${Math.round(stepScores[i]*100)}%`:''}</span></div>`).join('');if(index<0){$('coachTitle').textContent='Start the camera';$('coachText').textContent='Your camera preview will appear before hand recognition starts.';$('coachList').innerHTML=''}else if(index<5){const item=STEPS[index];$('coachTitle').textContent=item.name;$('coachText').textContent=item.guide;$('coachList').innerHTML=item.checks.map(x=>`<div class="coach-check">${x}</div>`).join('')}else{$('coachTitle').textContent='All five stages checked';$('coachText').textContent='The complete sequence was observed.';$('coachList').innerHTML=''}setSessionControls()}
function reset(){step=0;holdSince=0;gapUntil=0;baseline=null;stepScores=[0,0,0,0,0];mode='idle';eventPosted=false;showRetry=false;$('mouthZone').classList.add('hidden');$('mouthZone').classList.remove('near');ctx.clearRect(0,0,canvas.width,canvas.height);render()}
function handInfo(hand){const wrist=hand[0],palm=hand[9],pairs=[[8,6],[12,10],[16,14],[20,18]];let fingers=0;for(const [tip,pip] of pairs)if(hand[tip].y<hand[pip].y)fingers++;if(distance(hand[4],wrist)>distance(hand[3],wrist)*1.08)fingers++;const open=fingers>=4;const near=[hand[8],hand[12],hand[0]].some(p=>Math.hypot(p.x-CONFIG.mouthX,p.y-CONFIG.mouthY)<CONFIG.mouthRadius);return {fingers,open,near}}
function palmPixels(hand){if(!video.videoWidth)return null;const size=Math.max(30,Math.round(video.videoWidth*distance(hand[0],hand[9])*.7));const x=Math.min(Math.max(0,hand[9].x*video.videoWidth-size/2),video.videoWidth-size),y=Math.min(Math.max(0,hand[9].y*video.videoHeight-size/2),video.videoHeight-size);cropCtx.clearRect(0,0,48,48);cropCtx.drawImage(video,x,y,size,size,0,0,48,48);lastCropBox={x,y,size};return cropCtx.getImageData(0,0,48,48).data}
function objectDelta(hand){const pixels=palmPixels(hand);if(!pixels||!baseline)return 0;let total=0;for(let i=0;i<pixels.length;i+=4)total+=(Math.abs(pixels[i]-baseline[i])+Math.abs(pixels[i+1]-baseline[i+1])+Math.abs(pixels[i+2]-baseline[i+2]))/3;return total/(pixels.length/4)/255}
function saveBaseline(hand){baseline=palmPixels(hand)}
function drawHand(hand){if(!video.videoWidth)return;canvas.width=video.videoWidth;canvas.height=video.videoHeight;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.lineWidth=4;ctx.strokeStyle='#70e0a2';ctx.fillStyle='#fff';const links=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[17,18],[18,19],[19,20],[0,17]];for(const [a,b] of links){ctx.beginPath();ctx.moveTo(hand[a].x*canvas.width,hand[a].y*canvas.height);ctx.lineTo(hand[b].x*canvas.width,hand[b].y*canvas.height);ctx.stroke()}for(const p of hand){ctx.beginPath();ctx.arc(p.x*canvas.width,p.y*canvas.height,5,0,Math.PI*2);ctx.fill()}}
function nextStage(score,notice){stepScores[step]=score;step++;holdSince=0;gapUntil=Date.now()+CONFIG.gapMs;lastProgressAt=Date.now();feedback('neutral','Small pause',`${notice} Get ready for the next stage.`);render()}
function holdCheck(ok,ms,goodTitle,goodText,badTitle,badText,success){if(!ok){holdSince=0;feedback('bad',badTitle,badText);return}if(!holdSince)holdSince=Date.now();const remaining=Math.max(0,ms-(Date.now()-holdSince));if(remaining){feedback('good',goodTitle,`${goodText} Hold for ${Math.ceil(remaining/100)/10}s.`);return}holdSince=0;success()}
function updateDebugPanel(delta,objectPresent){const readout=$('debugReadout');if(!readout)return;readout.textContent=`delta=${delta.toFixed(3)} threshold=${CONFIG.objectThreshold.toFixed(3)} → ${objectPresent?'OBJECT PRESENT':'no object / empty'}`;readout.style.color=objectPresent?'#2d9b65':'#a54738';const debugCanvas=$('debugPreview');if(debugCanvas&&lastCropBox&&video.videoWidth){const dctx=debugCanvas.getContext('2d');dctx.imageSmoothingEnabled=false;dctx.clearRect(0,0,96,96);dctx.drawImage(video,lastCropBox.x,lastCropBox.y,lastCropBox.size,lastCropBox.size,0,0,96,96)}}

function onResults(result){if(mode==='idle'||mode==='done'||mode==='demo')return;const hand=result.multiHandLandmarks?.[0];if(!hand){ctx.clearRect(0,0,canvas.width,canvas.height);$('mouthZone').classList.remove('near');feedback('bad','Hand not detected','Move your hand fully into the camera view.');return}drawHand(hand);const info=handInfo(hand);const delta=objectDelta(hand),objectPresent=delta>CONFIG.objectThreshold,emptyPalm=delta<=CONFIG.objectThreshold;updateDebugPanel(delta,objectPresent);$('mouthZone').classList.toggle('near',info.near);if(Date.now()<gapUntil){feedback('neutral','Pause','Wait a moment, then follow the next instruction.');return}
  if(step===0)holdCheck(info.open&&emptyPalm,CONFIG.palmHold,'Empty palm detected','Keep your empty palm still.','Show your empty palm','Keep the palm empty, spread five fingers, and face it to the camera.',()=>{saveBaseline(hand);nextStage(.95,'Now pick up the tablet or test object.')});
  else if(step===1)holdCheck(objectPresent,CONFIG.objectHold,'Tablet detected','Keep the object visible to the camera.','Pick up the tablet','Hold the object so the camera can see it near your palm.',()=>nextStage(.9,'Tablet detected. Now move it to your mouth.'));
  else if(step===2)holdCheck(info.near&&objectPresent,CONFIG.mouthHold,'Tablet at mouth','Keep the tablet at the green oval.','Move tablet to mouth','Keep the tablet in your hand and move it into the mouth oval.',()=>nextStage(.9,'Mouth stage complete. Remove the tablet and show an empty palm.'));
  else if(step===3)holdCheck(info.open&&emptyPalm,CONFIG.palmHold,'Empty palm detected','Keep the palm open and empty.','Show empty palm again','Remove the tablet, spread five fingers, and face the empty palm to the camera.',()=>nextStage(.95,'Empty palm confirmed. Get ready to drink water.'));
  else if(step===4)holdCheck(info.near&&objectPresent,CONFIG.waterHold,'Water position detected','Keep the cup or test object at the green oval.','Bring water to mouth','Bring a cup or visible test object to the mouth oval and hold it there.',()=>{stepScores[4]=.85;mode='done';postVerificationEvent();feedback('good','All five stages correct','The complete tablet-and-water gesture sequence was observed.');render()})
}
async function track(){if(!tracking||!hands)return;if(mode==='live'&&Date.now()-lastProgressAt>SESSION_TIMEOUT_MS){pauseSession();return}const trackState=stream?.getVideoTracks?.()[0];if(trackState?.readyState==='ended'){cameraFailure('The camera connection was lost. Press Try again to reconnect.');return}if(video.readyState>=2&&video.videoWidth)try{await hands.send({image:video})}catch(error){cameraFailure('The hand tracker stopped. Press Try again to reconnect.')}if(tracking)requestAnimationFrame(track)}
async function startHands(){if(!window.Hands){cameraFailure('The hand tracker did not load. Check internet access, then press Try again.');return}hands=new Hands({locateFile:file=>`https://cdn.jsdelivr.net/npm/@mediapipe/hands/${file}`});hands.setOptions({maxNumHands:1,modelComplexity:0,minDetectionConfidence:.55,minTrackingConfidence:.55});hands.onResults(onResults);tracking=true;track()}
async function startCamera(){if(location.protocol==='file:'){cameraBadge('error','Use localhost');feedback('bad','Open through the local server','Use the localhost address, not the file directly.');return}if(!navigator.mediaDevices?.getUserMedia){cameraBadge('error','Camera unavailable');feedback('bad','Camera API unavailable','Use Chrome at a localhost address or HTTPS.');return}stopCameraTracks();reset();mode='live';showRetry=false;lastProgressAt=Date.now();setCameraMessage('Connecting to camera...');cameraBadge('','Connecting...');feedback('neutral','Connecting to camera','Allow camera access if Chrome asks.');try{stream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});video.srcObject=stream;video.onloadeddata=()=>{cameraBadge('live','Camera preview is live');setCameraMessage('Show your empty hand')};await video.play();$('mouthZone').classList.remove('hidden');feedback('neutral','Step 1: empty hand','Show five open fingers with nothing in your palm.');setCameraMessage('Show empty hand');await startHands();setSessionControls()}catch(error){const messages={NotAllowedError:'Chrome or Windows blocked camera access.',NotFoundError:'No camera was found.',NotReadableError:'The camera is busy in another app.',SecurityError:'Use Chrome at a localhost address or HTTPS.'};cameraFailure(messages[error.name]||`${error.name}: ${error.message||'unknown error'}`)}}
function demo(){if(demoTimer)clearInterval(demoTimer);mode='demo';reset();mode='demo';let i=0;const events=[['good','Empty palm detected','Now pick up a tablet or test object.'],['bad','Tablet not detected','Pick up the object and keep it visible.'],['good','Tablet detected','Pause, then move it to your mouth.'],['good','Tablet at mouth','Pause, then remove the tablet.'],['bad','Palm is not empty','Remove the tablet and show your empty palm.'],['good','Empty palm detected','Pause, then get a cup.'],['bad','Water not detected','Bring the cup to the mouth oval.'],['good','All five stages correct','The full sequence was observed.']];const tick=()=>{const e=events[i++];if(!e){clearInterval(demoTimer);mode='done';stepScores=[.95,.9,.9,.95,.85];render();return}feedback(e[0],e[1],e[2]);if(e[0]==='good'&&step<5){stepScores[step]=[.95,.9,.9,.95,.85][step];step++}render()};$('mouthZone').classList.remove('hidden');tick();demoTimer=setInterval(tick,900)}
const thresholdSlider=$('thresholdSlider');
if(thresholdSlider){thresholdSlider.value=CONFIG.objectThreshold;thresholdSlider.oninput=event=>{CONFIG.objectThreshold=Number(event.target.value);$('thresholdValue').textContent=CONFIG.objectThreshold.toFixed(3)}}
if($('alarmStartBtn'))$('alarmStartBtn').onclick=acknowledgeReminder;
$('unlockOverlay')?.addEventListener('pointerdown',unlockAudio,{once:true});
document.body.addEventListener('pointerdown',unlockAudio,{once:true});
$('startBtn').onclick=startCamera;$('demoBtn').onclick=demo;$('resetBtn').onclick=()=>{stopCameraTracks();reset();setCameraMessage('Click Start camera');cameraBadge('','Camera off');feedback('neutral','Ready','Start the camera, then follow the guide.')};$('retryBtn').onclick=startCamera;$('startWalkBtn')?.addEventListener('click',startWalk);$('finishWalkBtn')?.addEventListener('click',()=>finishWalk(false));reset();renderWalkPanel();
loadRoutineContext();pollReminders();setInterval(pollReminders,20000);
